# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\edit.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(645, 364)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/file-text.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("* {\n"
"    border: none;\n"
"    margin: 0;\n"
"    padding: 0;\n"
"    color: rgb(85, 170, 255);\n"
"    color: rgb(255, 255, 255);\n"
"    background-color:rgb(0, 139, 139);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.id_line = QtWidgets.QLineEdit(self.frame_2)
        self.id_line.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color:rgb(0, 0, 0);")
        self.id_line.setObjectName("id_line")
        self.gridLayout_2.addWidget(self.id_line, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 1)
        self.generator_line = QtWidgets.QLineEdit(self.frame_2)
        self.generator_line.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color:rgb(0, 0, 0);")
        self.generator_line.setObjectName("generator_line")
        self.gridLayout_2.addWidget(self.generator_line, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.ip_line = QtWidgets.QLineEdit(self.frame_2)
        self.ip_line.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color:rgb(0, 0, 0);")
        self.ip_line.setObjectName("ip_line")
        self.gridLayout_2.addWidget(self.ip_line, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 2, 1, 1)
        self.temp_line = QtWidgets.QLineEdit(self.frame_2)
        self.temp_line.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color:rgb(0, 0, 0);")
        self.temp_line.setObjectName("temp_line")
        self.gridLayout_2.addWidget(self.temp_line, 1, 3, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 2, 3, 1, 1)
        self.attach = QtWidgets.QCheckBox(self.frame_2)
        self.attach.setObjectName("attach")
        self.gridLayout_2.addWidget(self.attach, 2, 1, 1, 1)
        self.dettach = QtWidgets.QCheckBox(self.frame_2)
        self.dettach.setObjectName("dettach")
        self.gridLayout_2.addWidget(self.dettach, 2, 2, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Edit Generator(Attach/Detach)"))
        self.label_4.setText(_translate("Form", "ID"))
        self.label_5.setText(_translate("Form", "Generator"))
        self.label_2.setText(_translate("Form", "IP/Port"))
        self.label_3.setText(_translate("Form", "Templates"))
        self.pushButton.setText(_translate("Form", "Save"))
        self.attach.setText(_translate("Form", "Attach"))
        self.dettach.setText(_translate("Form", "Dettach"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
